Repository pharmaverse/admiral, pull requests merged in 2022-05, with the labels that each got.

#1111 950 deprecate derive vars suppqual
  NAMESPACE
  NEWS.md
  R/admiral-package.R
  R/assertions.R
  R/derive_vars_suppqual.R
  inst/templates/ad_adae.R
  inst/templates/ad_adcm.R
  inst/templates/ad_advs.R
  man/admiral-package.Rd
  man/convert_date_to_dtm.Rd
  man/convert_dtc_to_dt.Rd
  man/convert_dtc_to_dtm.Rd
  man/derive_var_base.Rd
  man/derive_var_disposition_status.Rd
  man/derive_var_extreme_flag.Rd
  man/derive_var_worst_flag.Rd
  man/derive_vars_dt.Rd
  man/derive_vars_dtm.Rd
  man/derive_vars_merged.Rd
  man/derive_vars_merged_dt.Rd
  man/derive_vars_merged_dtm.Rd
  man/derive_vars_suppqual.Rd
  man/impute_dtc.Rd
  man/use_ad_template.Rd
  renv.lock
  tests/testthat/test-deprecation.R
  tests/testthat/test-derive_vars_suppqual.R
  vignettes/admiral.Rmd
  vignettes/bds_exposure.Rmd
  vignettes/bds_finding.Rmd
  vignettes/occds.Rmd
  vignettes/programming_strategy.Rmd
Labels: metadata

#860 850 create adpp
  .gitignore
  NEWS.md
  R/data.R
  data/admiral_adpp.rda
  inst/templates/ad_adpp.R
  man/admiral_adpp.Rd
  man/use_ad_template.Rd
  tests/testthat/test-user_helpers.R
Labels: ADPP

#1175 Closes #1156 - Code coverage reports without codecov
  .github/workflows/R-CMD-check.yml
  .github/workflows/code-coverage.yml
  .github/workflows/codecov.yml
  .github/workflows/lintr.yaml
  .github/workflows/man-pages.yml
  .github/workflows/pkgdown.yml
  .github/workflows/spellcheck.yml
  .github/workflows/style.yml
  README.md
  codecov.yml
Labels: enhancement
