Repository pharmaverse/admiral, pull requests merged in 2023-02, with the labels that each got.

#1690 Closes #1650 Removed unit check for HYPERURICEMIA (version 5 only)
  NEWS.md
  data/atoxgr_criteria_ctcv4.rda
  data/atoxgr_criteria_ctcv5.rda
  inst/adlb_grading/adlb_grading_spec.xlsx
  tests/testthat/test-derive_var_atoxgr.R
Labels: ADLB, release Q1-2023

#1643 Closes #1640 add nominal time to create single dose dataset
  NEWS.md
  R/create_single_dose_dataset.R
  R/globals.R
  inst/WORDLIST
  man/create_single_dose_dataset.Rd
  tests/testthat/test-create_single_dose_dataset.R
Labels: enhancement, ADPC, ADNCA, release Q1-2023, ADPPK

#1651 Closes #1639 create vignette for pk programming
  NEWS.md
  docs/pkgdown.yml
  inst/WORDLIST
  vignettes/pk_adnca.Rmd
Labels: documentation, ADPC, ADNCA, PK, release Q1-2023

#1756 Closes #1754 changes for testthat3e@devel
  DESCRIPTION
  NEWS.md
  tests/testthat.R
  tests/testthat/test-derive_date_vars.R
  tests/testthat/test-derive_merged.R
  tests/testthat/test-derive_param_computed.R
  tests/testthat/test-derive_param_wbc_abs.R
  tests/testthat/test-user_helpers.R
  tests/testthat/test-user_utils.R
Labels: release Q1-2023

#1610 Closes #1408 Enhance example of `create_single_dose_dataset()`
  NEWS.md
  R/create_single_dose_dataset.R
  _pkgdown.yml
  docs/pkgdown.yml
  man/create_single_dose_dataset.Rd
Labels: contribution
